production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dt1onamu3t4un
  username: znnmschotekqxc
  password: htPrnNZnKJ8Ai1n_EugVMuzJzP
  host: ec2-54-204-42-135.compute-1.amazonaws.com
  port: 5432